crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from api import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginPage, name='loginPage'),
    # path('',views.demo,name='loginPage'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('delete_company_ajax',views.delete_company_ajax,name='delete_company_ajax'),
    path('user_login', views.user_login, name="user_login"),
    path('logout_user', views.user_logout, name="user_logout"),
    path('dashboard', views.home, name="dashboard"),
    path('user_profile', views.user_profile, name="user_profile"),
    path('manage_companies', views.manage_companies,
         name='manage_companies'),
    path('add_company', views.add_company, name="add_company"),
    path('add_company_save', views.add_company_save,name="add_company_save"),
    path('edit_company/<str:company_id>',views.edit_company, name="edit_company"),
    path('delete_company/<str:company_id>',views.delete_company, name="delete_company"),
    path('edit_company_save', views.edit_company_save,name="edit_company_save"),
    
    path('manage_employees', views.manage_employees,name='manage_employees'),
    path('add_employee', views.add_employee, name="add_employee"),
    path('edit_employee/<str:employee_id>',views.edit_employee, name="edit_employee"),
    path('company/<str:company_id>',views.company_detail, name="company_detail"),
    path('delete_employee/<str:employee_id>',views.delete_employee, name="delete_employee"),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.core.files.images import get_image_dimensions



#table for Companies
def validate_image(fieldfile_obj):
    if  fieldfile_obj:
        w, h = get_image_dimensions(fieldfile_obj)
    if w < 100:
        raise ValidationError("The image is %i pixel narrow. It's supposed to be wider than 100px" % w)
    if h < 100:
        raise ValidationError("The image is %i pixel low. It's supposed to be higher than 100px" % h)
class Company(models.Model):
    name=models.CharField(max_length=50,blank=False,unique=True)
    email=models.EmailField(max_length=50,blank=False,unique=True)
    logo=models.ImageField( upload_to="logo",validators=[validate_image],blank=True,null=True)
    website=models.URLField(max_length=250,db_index=True, unique=True, blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
# def clean(self):
#     if  self.logo:
#         w, h = get_image_dimensions(self.logo)
#         if w < 100:
#             raise ValidationError("The image is %i pixel narrow. It's supposed to be wider than 100px" % w)
#         if h < 100:
#             raise ValidationError("The image is %i pixel low. It's supposed to be higher than 100px" % h)
#table for Custom User
class CustomUser(AbstractUser):
   
    company=models.ForeignKey(Company,blank=True,null=True,on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    mobile_num_regex = RegexValidator(regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!")
    phone_number=models.CharField(validators=[mobile_num_regex],max_length=12)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

api/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import widgets
from .models import Company

class CompanyForm(ModelForm):
    
    class Meta():
        model=Company
        # exclude=('maker',)
        fields='__all__'

api/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from api.EmailBackEnd import EmailBackEnd
from django.urls import reverse
from django.contrib.auth.decorators import login_required,permission_required
from api.models import Company,CustomUser
from django.views.decorators.csrf import csrf_exempt

def showdemo(request):
    return render(request,'demo.html')
# Create your views/controllers here.
def loginPage(request):
    return render(request,'login.html')
def home(request):
    company_count=Company.objects.all().count()
    employee_count=CustomUser.objects.all().count()
    last_ten_employees = CustomUser.objects.all().order_by('-id')[:10][::-1]
    context={'companies':company_count,'employees':employee_count,'last_ten_employees':last_ten_employees}
    return render(request,'dashboard.html',context)
#log in a user using an email and a password
def user_login(request):
    if request.method!="POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
         user=EmailBackEnd.authenticate(request,username=request.POST.get("email"),password=request.POST.get("password"))
         if user!=None:
             login(request,user)
             return HttpResponseRedirect('/dashboard')
          

         else:
            messages.error(request,"Invalid Login Details")
            return HttpResponseRedirect("/")

#logs out a logged in user
def user_logout(request):
    logout(request)
    return HttpResponseRedirect("/")
def user_profile(request):
    if request.method!="POST":
        user=CustomUser.objects.get(id=request.user.id)
        return render(request,"user_profile.html",{"user":user})
    else:
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        password=request.POST.get("password")
        try:
            customuser=CustomUser.objects.get(id=request.user.id)
            customuser.first_name=first_name
            customuser.last_name=last_name
            if password!=None and password!="":
                customuser.set_password(password)
            customuser.save()
            messages.success(request, "Successfully Updated Profile")
            return HttpResponseRedirect(reverse("loginPage"))
        except:
            messages.error(request, "Failed to Update Profile")
            return HttpResponseRedirect(reverse("loginPage"))



#create a company
@login_required
def manage_companies(request):
    companies=Company.objects.all()
    context={"companies":companies}
    return render(request,"manage_companies.html",context)
@login_required
def add_company(request):
    return render(request,"add_company.html")

@login_required
def add_company_save(request):
    """
    This method is for adding a new company

    Extended description of function.
    arg(request)

    """
    if request.method!="POST":
        return HttpResponse("Method Not Allowed")
    else:
        company_name=request.POST.get("company_name")
        logo=request.FILES.get("logo")
        email=request.POST.get("email")
        website=request.POST.get("website")
        try:
            company_model=Company(name=company_name,email=email,website=website,logo=logo)
            company_model.save()
            messages.success(request,"Successfully Added A Company")
            return HttpResponseRedirect(reverse("add_company"))
        except:
            
            messages.error(request,"Failed to Add A Company")
            return HttpResponseRedirect(reverse("add_company"))
@login_required
def edit_company(request,company_id):
    company=Company.objects.get(id=company_id)
    return render(request,"edit_company.html",{"company":company,"id":company_id})
@login_required
def edit_company_save(request):
    if request.method!="POST":
        return HttpResponse("<h2>Method Not Allowed</h2>")
    else:
        company_id=request.POST.get("company_id")
        name=request.POST.get("company_name")
        email=request.POST.get("email")
        logo=request.POST.get("logo")
        website=request.POST.get("website")
        try:
            company=Company.objects.get(id=company_id)
            company.name=name
            company.logo=logo
            company.website=website
            company.email=email
            company.save()
            messages.success(request,"Successfully Edited Company ")
            return HttpResponseRedirect(reverse("manage_companies"))
        except:
            messages.error(request,"Failed to Edit Company Details")
            return HttpResponseRedirect("/edit_company/"+company_id)
@login_required
def delete_company(request,company_id):
    if request.method!="POST":
        company=Company.objects.get(id=company_id)
        return render(request,"delete_company.html",{"company":company,"id":company_id})
    else:
        try:
            company=Company.objects.get(id=company_id)
            company.delete()
            messages.success(request,"Successfully Deleted Company ")
            return HttpResponseRedirect(reverse("manage_companies"))
        except:
            messages.success(request,"Successfully Deleted Company ")
            return HttpResponseRedirect(reverse("manage_companies"))

#employees controllers
@login_required
def manage_employees(request):
    employees=CustomUser.objects.all()
    context={"employees":employees}
    return render(request,"manage_employees.html",context)
@login_required
def company_detail(request,company_id):
    company=Company.objects.get(id=company_id)
    context={"company":company}
    return render(request,"company_detail.html",context)

@login_required
def add_employee(request):
    """
    This method is for adding a new employee

    Extended description of function.
    arg(request)

    """
    if request.method!="POST":
        companies=Company.objects.all()
    
        context={"companies":companies}
        return render(request,"add_employee.html",context)
    else:
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        company=request.POST.get("company")
        phone_number=request.POST.get("phone_number")
        
        username=request.POST.get("username")
        password=request.POST.get("password")
        try:
            user=CustomUser.objects.create_user(username=username,password=password,last_name=last_name,first_name=first_name)
            company_obj=Company.objects.get(id=company)
            user.company=company_obj
            user.email=email
            user.phone_number=phone_number
            user.save()
            
            messages.success(request,"Successfully Added  Employee")
            return HttpResponseRedirect(reverse("manage_employees"))
        except:
            user.delete()
            messages.error(request,"Failed to Add Employee")
            return HttpResponseRedirect(reverse("add_employee"))
@login_required
def edit_employee(request,employee_id):
    if request.method!="POST":
        employee=CustomUser.objects.get(id=employee_id)
        return render(request,"edit_employee.html",{"employee":employee,"id":employee_id})
    else:
       
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        username=request.POST.get("username")
        phoneNumber=request.POST.get("phoneNumber")
        try:
            user=CustomUser.objects.get(id=employee_id)
            user.first_name=first_name
            user.last_name=last_name
            user.email=email
            user.username=username
            user.phone_number=phoneNumber
            user.save()
            messages.success(request,"Successfully Edited Employee")
            return HttpResponseRedirect(reverse("manage_employees"))
        except:
            messages.error(request,"Failed to Edit Employee")
            return HttpResponseRedirect(reverse("edit_employee",kwargs={"employee_id":employee_id}))
@login_required
def delete_employee(request,employee_id):
    if request.method!="POST":
        employee=CustomUser.objects.get(id=employee_id)
        return render(request,"delete_employee.html",{"employee":employee,"id":employee_id})
    else:
        try:
            employee=CustomUser.objects.get(id=employee_id)
            employee.delete()
            messages.success(request,"Successfully Deleted Employee ")
            return HttpResponseRedirect(reverse("manage_employees"))
        except:
            messages.success(request,"Successfully Deleted Employee ")
            return HttpResponseRedirect(reverse("manage_employees"))
@csrf_exempt
def delete_company_ajax(request):
    try:
        id=request.POST.get("id")
        
        company=Company.objects.get(id=id)
        company.delete()
        messages.success(request,"Successfully Deleted Company ")
        return HttpResponse("True")
    except:
        messages.error(request,"Failed to Delete Company ")
        return HttpResponse("False")
        

api/templates/add_company.html
{% extends "base.html"%} {% block page_title %} Create Company{% endblock page_title %} {%block main_content%}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                
                <div class="card ">

                   
                    <form role="form" action="/add_company_save" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="form-group">
                                <label>Company Name</label>
                                <input type="text" class="form-control" name="company_name" placeholder="Company Name">
                            </div>
                            <div class="form-group">
                                <label>Company Email</label>
                                <input type="email" class="form-control" name="email" placeholder="Company Email">
                            </div>

                            <div class="form-group">
                                <label>Website</label>
                                <input type="url" class="form-control" placeholder="Company Website" name="website">
                            </div>
                            <div class="form-group">
                                <label>Logo</label>
                                <input type="file" class="form-control" placeholder="logo" name="logo">
                            </div>
                            

                        </div>
                        

                        <div>
                            <button type="submit" class="btn  btn-block">Save</button>
                        </div>
                    </form>
                </div>
                



            </div>
        </div>
    </div>
</section>
{%endblock main_content%} {%block custom_js %}
{% if messages %} {% for message in messages %}
<script type=text/javascript>
    $(document).ready(function() {
        
        toastr.options = {

"progressBar": true,
"showDuration": "20",

};

toastr.{{message.tags}}('{{message}}');

       
        
});
    
</script>
{% endfor %} {% endif %}

{%endblock custom_js%}

api/templates/add_employee.html
{% extends "base.html"%} {% block page_title %} Create Employee{% endblock page_title %} {%block main_content%}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                
                <div class="card ">

                   
                    <form role="form" action="" method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="form-group">
                                <label>Email address</label>
                                <input type="email" class="form-control" name="email" placeholder="Enter email">
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" placeholder="Password" name="password">
                            </div>
                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" placeholder="First Name" name="first_name">
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" placeholder="Last Name" name="last_name">
                            </div>
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control" placeholder="Username" name="username">
                            </div>
                            <div class="form-group">
                                <label>Company</label>
                                <select class="form-control" name="company">
                                    {% for company in companies %}
                                    <option value="{{company.id}}">{{company.name}}</option>
                                    {%endfor%}
                                 </select>

                            </div>
                           
                            <div class="form-group">
                                <label>Phone Number</label>
                                <input type="text" class="form-control" placeholder="Phone Number" name="phone_number">
                            </div>
                            

                        <div>
                            <button type="submit" class="btn  btn-block">Save</button>
                        </div>
                    </form>
                </div>
               



            </div>
        </div>
    </div>
</section>
{%endblock main_content%} {%block custom_js %}
{% if messages %} {% for message in messages %}
<script type=text/javascript>
    $(document).ready(function() {
        
        toastr.options = {

"progressBar": true,
"showDuration": "100",

};

toastr.{{message.tags}}('{{message}}');

       
        
});
    
</script>
{% endfor %} {% endif %}

{%endblock custom_js%}

api/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> CRM</title>
    <!-- for the website icon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css' %}">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{%static 'plugins/datatables-bs4/css/dataTables.bootstrap4.css'%}">
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{%static 'plugins/summernote/summernote-bs4.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"> {%block custom_css%} {%endblock custom_css%}
    <!-- Google Font: Source Sans Pro -->
    <style>
        .form-group>input:focus {
            font-size: 12px;
            -moz-box-shadow: 0 0 4px #f29e24;
            -webkit-box-shadow: 0 0 4px #f29e24;
            box-shadow: 0 0 4px #f29e24;
            border: 1px solid #f29e24;
        }
        
        .btn {
            background-color: #f29e24 !important;
        }
        
        .badge-warning {
            background-color: #f29e24 !important;
        }
        
        .card {
            margin-left: 1px;
            margin-right: 1px;
            height: 94%;
            -moz-box-shadow: 0 0 10px lightgray !important;
            -webkit-box-shadow: 0 0 10px lightgray !important;
            box-shadow: 0 0 10px lightgray !important;
        }
        
    </style>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>

            </ul>

            <!-- SEARCH FORM -->

            <!-- Right navbar links -->
            <h3>CRM</h3>
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <li class="nav-item">
                    <a class="nav-link" href="">
         Hello , {{request.user.username}}
       </a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_logout' %}">
         Logout
       </a>
                </li>
            </ul>

        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        {% include "sidebar_template.html" with user=user id=id %}
        <!-- Content Wrapper. Contains page content -->


        <!-- /.content-header -->
        <div class="content-wrapper" style="background-color:#fff">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">
                                {% block page_title %} {% endblock page_title %}
                            </h1>
                        </div>
                        <!-- /.col -->

                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>

            <!-- Main content -->
            {% block main_content%}{% endblock main_content%}
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        {%include "footer.html" %}
        <!-- Control Sidebar -->

        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    <script src="{%static 'plugins/jquery/jquery.min.js' %} "></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %} "></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
    <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{%static 'plugins/chart.js/Chart.min.js' %} "></script>
    <!-- Sparkline -->
    <script src="{% static 'plugins/sparklines/sparkline.js' %} "></script>
    <!-- JQVMap -->
    <!-- DataTables -->
    <script src="{%static 'plugins/datatables/jquery.dataTables.js'%}"></script>
    <script src="{%static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js'%}"></script>
    <script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %} "></script>
    <script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %} "></script>
    <!-- jQuery Knob Chart -->
    <script src="{%static 'plugins/jquery-knob/jquery.knob.min.js' %} "></script>
    <!-- daterangepicker -->
    <script src="{%static 'plugins/moment/moment.min.js' %} "></script>
    <script src="{%static 'plugins/daterangepicker/daterangepicker.js' %} "></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{%static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %} "></script>
    <!-- Summernote -->
    <script src="{% static 'plugins/summernote/summernote-bs4.min.js' %} "></script>
    <!-- overlayScrollbars -->
    <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js "></script>
    <!-- AdminLTE App -->

    <script src="{%static 'dist/js/adminlte.js' %} "></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{%static 'dist/js/pages/dashboard.js' %} "></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{%static 'dist/js/demo.js' %} "></script>
    

    <script>
        (function($) {

            $('.clickable-row').css('cursor', 'pointer');
            $(".clickable-row").click(function() {
                window.location = $(this).data("href");
            });
        })(jQuery)
    </script>

    {%block custom_js %} {%endblock custom_js%}
</body>

</html>

api/templates/company_detail.html
{% extends "base.html"%} {% load static %} {% block page_title %} {{company.name}} Employees{% endblock page_title %} {% block main_content %}
<section class="content">
    <div class="container-fluid">
        
            <div class="card">
                <div class="card-body table-responsive ">
                    <table id="employees-table" class="table table-bordered table-hover" data-page-length='10'>
                        <thead>
                            <tr>
                                <th>S/N</th>
                                <th>Employee Name</th>
        
                                <th>Email</th>
                                <th>Company</th>
                                <th>Phone</th>
        
                                <!-- <th>Date Created</th> -->
                                <th>Edit</th>
                                <th>Delete</th>
                                
                            </tr>
                        </thead>
                        <tbody>
        
                            {% for employee in company.customuser_set.all  %}
                            <tr>
        
                                <td>{{ forloop.counter}}</td>
                                <td>{{ employee.first_name }} {{employee.last_name}}</td>
        
                                <td>{{ employee.email }}</td>
                                <td>{{ employee.company.name }}</td>
                                <td>{{employee.phone_number}}</td>
        
                                
        
                                <td>
                                    <a href="{% url 'edit_employee' employee.id %}" class="btn btn-tool">
                                        <i style="color:black"class="fas fa-edit"></i></td>
                                <td>
                                    <a href="{% url 'delete_employee' employee.id %}" class="btn btn-tool">
                                        <i style="color:black"class="fas fa-times"></i>
                                    </a>
                                </td>
                                
                            </tr>
                            {% endfor %}
        
                        </tbody>
                    </table>
                </div>
                </div>
                <!-- /.card-body -->
        
        
    </div>
   
</section>



{%endblock main_content%} {% block custom_js %}

<script type="text/javascript">
    $(document).ready(function() {
        $('#employees-table').DataTable({
            "autoWidth": false,
        });
    });
</script>

{%endblock custom_js%}

api/templates/delete_company.html
{% extends "base.html"%} {% block page_title %} Home {% endblock page_title %} {%block main_content%}
<section class="content">
    <div class="container-fluid">
        <div class="row" style="margin:5% auto;display: flex;margin-left:25%">
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-danger">
                    <div class="card-header">
                        <h3 class="card-title">Delete Record</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="" method="POST">
                        {% csrf_token %}

                        <div class="alert">
                            <p>Are you sure you want to delete {{ company.name }} Company?</p>
                            <p>All contents attached to this record will be deleted</p>
                        </div>


                        <div class="card-footer">
                            <button type="submit"  class="btn-danger  btn-block">Confirm</button>
                        </div>
                    </form>
                </div>
                <!-- /.container-fluid -->
</section>


{% endblock main_content %}

api/templates/delete_employee.html
{% extends "base.html"%} {% block page_title %} Home {% endblock page_title %} {%block main_content%}
<section class="content">
    <div class="container-fluid">
        <div class="row" style="margin:5% auto;display: flex;margin-left:25%">
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-danger">
                    <div class="card-header">
                        <h3 class="card-title">Delete Employee Record</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="" method="POST">
                        {% csrf_token %}

                        <div class="alert">
                            <p>Are you sure you want to delete this {{ employee.first_name }} {{employee.last_name}} Employee?</p>
                            <p>All contents attached to this record will be deleted</p>
                        </div>


                        <div class="card-footer">
                            <button type="submit"  class="btn-danger  btn-block">Confirm</button>
                        </div>
                    </form>
                </div>
                <!-- /.container-fluid -->
</section>


{% endblock main_content %}

api/templates/demo.html
<h1>Hello world</h1>

api/templates/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2021-2022 <a href="">Esther Waweru</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
  </footer>